name: ascii_app
description: ASCII Art Converter App - Convert images to ascii art on your phone.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  image: ^4.0.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/
  fonts:
    - family: Lucida Console
      fonts:
        - asset: fonts/lucida-console.ttf
    - family: Roboto
      fonts:
        - asset: fonts\Roboto-Regular.ttf
        - asset: fonts\Roboto-Light.ttf
          weight: 200
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"